{% set name = "owlready2" %}
{% set version = "0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/Owlready2/Owlready2-{{ version }}.tar.gz
  sha256: d13bf0ed36a8e7ddcac00107e79b3a83a4d7c7cb5ac3ca28543b462773d4e97f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip

test:
  imports:
    - owlready2
  commands:
    - pip check

about:
  home: https://bitbucket.org/jibalamy/owlready2
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Owlready2 is a module for ontology-oriented programming in Python.

  description: |
    Owlready2 is a module for ontology-oriented programming in Python. 
    It can load OWL 2.0 ontologies as Python objects, modify them, save 
    them, and perform reasoning via HermiT. Owlready2 includes an 
    optimized RDF quadstore.
  doc_url: http://owlready2.readthedocs.io/
  dev_url: https://bitbucket.org/jibalamy/owlready2

extra:
  recipe-maintainers:
    - jan-janssen
