{% set name = "owlready2" %}
{% set version = "0.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/Owlready2/Owlready2-{{ version }}.tar.gz
  sha256: 81d87640952b2b79d03f15f236897ce08287e1056f51371928c655d18acd51a7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip

test:
  imports:
    - owlready2
  commands:
    - pip check  # [not win]

about:
  home: https://bitbucket.org/jibalamy/owlready2
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Owlready2 is a module for ontology-oriented programming in Python.

  description: |
    Owlready2 is a module for ontology-oriented programming in Python. 
    It can load OWL 2.0 ontologies as Python objects, modify them, save 
    them, and perform reasoning via HermiT. Owlready2 includes an 
    optimized RDF quadstore.
  doc_url: http://owlready2.readthedocs.io/
  dev_url: https://bitbucket.org/jibalamy/owlready2

extra:
  recipe-maintainers:
    - jan-janssen
