{% set name = "owlready2" %}
{% set version = "0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/Owlready2/Owlready2-{{ version }}.tar.gz
  sha256: 9d61b717580856089ba1d56aafc67364fce361c7aceb1e5d824efb5bf5a6f20b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip

test:
  imports:
    - owlready2
  commands:
    - pip check

about:
  home: https://bitbucket.org/jibalamy/owlready2
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Owlready2 is a module for ontology-oriented programming in Python.

  description: |
    Owlready2 is a module for ontology-oriented programming in Python. 
    It can load OWL 2.0 ontologies as Python objects, modify them, save 
    them, and perform reasoning via HermiT. Owlready2 includes an 
    optimized RDF quadstore.
  doc_url: http://owlready2.readthedocs.io/
  dev_url: https://bitbucket.org/jibalamy/owlready2

extra:
  recipe-maintainers:
    - jan-janssen
