{% set name = "owlready2" %}
{% set version = "0.45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/Owlready2/{{ name }}-{{ version }}.tar.gz
  sha256: 44a501ace1bc5b7be1c2f5aa98dd14825c590ce0c5d4e3bc353f458df522dca7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pip

test:
  imports:
    - owlready2
  commands:
    - pip check  # [not win]

about:
  home: https://bitbucket.org/jibalamy/owlready2
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Owlready2 is a module for ontology-oriented programming in Python.

  description: |
    Owlready2 is a module for ontology-oriented programming in Python. 
    It can load OWL 2.0 ontologies as Python objects, modify them, save 
    them, and perform reasoning via HermiT. Owlready2 includes an 
    optimized RDF quadstore.
  doc_url: http://owlready2.readthedocs.io/
  dev_url: https://bitbucket.org/jibalamy/owlready2

extra:
  recipe-maintainers:
    - jan-janssen
