{% set name = "owlready2" %}
{% set version = "0.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/owlready2-{{ version }}.tar.gz
  sha256: 3c1b06dbe85df77dfa2de5a13ba1d11b4b8543c1c0ccdc5be252a81e3c0de55a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - pip
  run:
    - python

test:
  imports:
    - owlready2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/jibalamy/owlready2
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Owlready2 is a module for ontology-oriented programming in Python.
  description: |
    Owlready2 is a module for ontology-oriented programming in Python. 
    It can load OWL 2.0 ontologies as Python objects, modify them, save 
    them, and perform reasoning via HermiT. Owlready2 includes an 
    optimized RDF quadstore.
  doc_url: http://owlready2.readthedocs.io/
  dev_url: https://bitbucket.org/jibalamy/owlready2

extra:
  recipe-maintainers:
    - jan-janssen
