travis:
  secure:
    BINSTAR_TOKEN: M52KcSF4pt/RHx4T+/Xk5bU/T5a+5BRduMKqeoKx6GKVUGkS5xTsv+sHsX1rBMtjB8PsXPpSsqinD8w3lILSyb+fKM9JjQUI8N+FRTFdjn+PaTkaVXbE8eYolF4GcimdxJAiGNiIhrOpqm3YR3vXZTdUd4GG1O+bE8CfjTlXbK4DXLg23tV4joK7C5nK40K4WqVP1UeFDI0hDTGiyBiGdX3S5dHGbhJGefJiN3CCvm3Fetj668K3RkGNcobr/7Oo0s4Wlpd5kD95T9gLwv5NauFZbbvL3vtzloeRu4Pv6vzrkCBqm70uhwBI9opCe4da3lWcsARjwcB9b65YlZeJcru9VxuSBkw/5XSflWQX1cAjOF1rDkYEJmVcxCiop7SUpgQ23eNUHh3D7Ys3u7Kaej5wuAHrDemuTE9rEbakhUA6gwWhIvcKWNxB1HjMDnxHZLcmhPShnkPqYV3f+w7wvR+B9J9No4CdoaqayZtUaGeSCg7FFebWFd3MxCOMIp8qv6813zyG2ef9GtavscZd9ifg38kipD0576M5Z0MFVyD6W44ZZiUzk3iubdcjPXKgsMMdTFlQZRUXEWWftEpyGwyCXk1eWFnzKKK3dax+bVRwqRrQUMUwnAszpAQek4fenyUCFiKDU10uXrtLzTSfLKInJS3/ZpSYC28uqG2UetI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
